### ISSUE TITLE
need to check your installition guide!

### ISSUE THREAD

**Issue by Daqu** [iqiyi/auklet#3]
eg:when i go with **Install binary**,an error occured because of `sudo mv bin/auklet /usr/loca/bin`
it should be `sudo mv bin/auklet /usr/local/bin`. local not loca

though i can deploy and run auklet, but i got many little errors like this.

hope u can review your guide! thank you!

**Comment by bluesalt** [comment]
Thanks for the comment.  Will fix it soon.
BTW, It would be nice if you could create a PR.  We encourage any form of contribution!
